export const GET_DATA_POSITION_SUCCESS = 'GET_DATA_POSITION_SUCCESS';
export const GET_DATA_POSITION_FAILURE = 'GET_DATA_POSITION_FAILURE';
export const CREATE_DATA_POSITION_SUCCESS = 'CREATE_DATA_POSITION_SUCCESS';
export const CREATE_DATA_POSITION_FAILURE = 'CREATE_DATA_POSITION_FAILURE';
export const UPDATE_DATA_POSITION_SUCCESS = 'UPDATE_DATA_POSITION_SUCCESS';
export const UPDATE_DATA_POSITION_FAILURE = 'UPDATE_DATA_POSITION_FAILURE';
export const DELETE_DATA_POSITION_SUCCESS = 'DELETE_DATA_POSITION_SUCCESS';
export const DELETE_DATA_POSITION_FAILURE = 'DELETE_DATA_POSITION_FAILURE';
